services:
  rtype-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: rtype-server
    ports:
      - "4242:4242/udp"
    restart: unless-stopped
    networks:
      - rtype-net

  rtype-client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    container_name: rtype-client
    networks:
      - rtype-net

networks:
  rtype-net:
    driver: bridge
